version: "3.8"
services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4442-4444:4442-4444"
    networks:
      - grid

  chrome-node:
    image: selenium/node-chrome:latest
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    deploy:
      replicas: 2  # Number of Chrome nodes
    shm_size: 2gb
    depends_on:
      - selenium-hub
    networks:
      - grid

  firefox-node:
    image: selenium/node-firefox:latest
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    deploy:
      replicas: 2  # Number of Firefox nodes
    shm_size: 2gb
    depends_on:
      - selenium-hub
    networks:
      - grid

networks:
  grid:
    driver: bridge
